version: '3'
services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=ditoo_dev'
      - 'MYSQL_PASSWORD=ditooland123'
      - 'MYSQL_ROOT_PASSWORD=ditooland123'
      - 'MYSQL_USER=root'
    ports:
      - '3308:3306'
