spring:
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  docker:
    compose:
      enabled: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ditoo_dev
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: prometheus
logging:
  config: classpath:log4j22.xml
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace

