spring:
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
#        format_sql: true
    hibernate:
      ddl-auto: create
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace
