spring:
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
#        format_sql: true
    hibernate:
      ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include: prometheus
logging:
  config: classpath:log4j2.xml
