spring:
  flyway:
    enabled: false
  jpa:
    properties:
      hibernate:
#        format_sql: true
    hibernate:
      ddl-auto: create
  docker:
    compose:
      enabled: off
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/ditoo_dev
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: prometheus
logging:
  config: classpath:log4j22.xml
