name: continuous-deploy

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make application-dev.yml
        if: ${{ github.event.push.head.ref == 'main' }}
        env:
          PROPERTIES_DEV: ${{ secrets.PROPERTIES_DEV }}
        run: |
          cd ./src/main/resources
          touch ./application-dev.yml
          echo "${PROPERTIES_DEV}" > ./application-dev.yml
        shell: bash

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: build

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_DEPLOY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEPLOY_TOKEN }}

      - name: Docker Image Build
        run: |
          docker buildx build --platform linux/amd64 -t shb03323/cicd -f Dockerfile .

      - name: Docker Hub Push
        run: docker push shb03323/cicd

  cd:
    needs: ci
    runs-on: [ self-hosted, Linux, X64 ]

    steps:
      - name: Pull Latest Docker Image
        run: |
          sudo docker login --username ${{ secrets.DOCKERHUB_DEPLOY_USERNAME }} --password ${{ secrets.DOCKERHUB_DEPLOY_TOKEN }}
          if sudo docker inspect cicd-container &>/dev/null; then
            sudo docker stop cicd-container
            sudo docker rm -f cicd-container
            sudo docker image prune -af
          fi
          sudo docker pull shb03323/cicd:latest

      - name: Run Container
        run: |
          sudo docker run --name cicd-container -p 8080:8080 shb03323/cicd:latest 1>> build.log 2>> error.log &
